"""Add users_data to SplitwiseExpense

Revision ID: bd4b8734f2b6
Revises: 8b1d61d99c48
Create Date: 2026-05-01 19:57:45.598344

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd4b8734f2b6"
down_revision: Union[str, Sequence[str], None] = "8b1d61d99c48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "splitwise_expenses", sa.Column("users_data", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("splitwise_expenses", "users_data")
    # ### end Alembic commands ###
