"""add is_edited to transactions

Revision ID: f92aebafde1f
Revises: bd4b8734f2b6
Create Date: 2026-05-02 14:18:11.666285

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f92aebafde1f"
down_revision: Union[str, Sequence[str], None] = "bd4b8734f2b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "is_edited", sa.Boolean(), nullable=False, server_default=sa.text("0")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "is_edited")
    # ### end Alembic commands ###
